on: [workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ github.token }}" | docker login ghcr.io --username $ --password-stdin
      - run: DOCKER_BUILDKIT=1 docker build --tag ghcr.io/${{ github.repository_owner }}/nginx-spa .
      - run: docker push ghcr.io/${{ github.repository_owner }}/nginx-spa
